# Generated by Django 4.2.7 on 2023-12-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('cnic', models.IntegerField()),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
